name: Sync and Deploy Terraform Configuration

on:
  push:
    paths:
      - '**.tf'  # Trigger workflow on any Terraform file change
      - '**.tfvars'

jobs:
  sync-upload-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

     - name: Extract Azure Credentials
        id: extract-creds
        run: |
          CLIENT_ID=$(awk -F' *= *' '/client_id/ {print $2}' terraform/main.tf | tr -d '"')
          CLIENT_SECRET=$(awk -F' *= *' '/client_secret/ {print $2}' terraform/main.tf | tr -d '"')
          TENANT_ID=$(awk -F' *= *' '/tenant_id/ {print $2}' terraform/main.tf | tr -d '"')
          echo "::set-output name=client_id::$CLIENT_ID"
          echo "::set-output name=client_secret::$CLIENT_SECRET"
          echo "::set-output name=tenant_id::$TENANT_ID"

      - name: Log in to Azure CLI
        run: az login --service-principal -u ${{ steps.extract-creds.outputs.client_id }} -p ${{ steps.extract-creds.outputs.client_secret }} --tenant ${{ steps.extract-creds.outputs.tenant_id }}

      - name: Upload Terraform Files to Azure Storage
        run: |
          az storage blob upload-batch --account-name strepac --destination conepac --source . --pattern "*.tf" --overwrite --auth-mode login
        env:
          AZURE_STORAGE_ACCOUNT: "strepac"

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Initialize Terraform
        run: terraform init

      - name: Remove Local Terraform State File (if exists)
        run: rm -f terraform.tfstate

      - name: Apply Terraform Configuration
        env:
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve
