name: Azure Login via Terraform Credentials

on:
  push:
    paths:
      - '**.tf'  # Trigger workflow when Terraform file changes

jobs:
  azure-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Extract Azure Credentials from Terraform
        id: extract-creds
        run: |
          CLIENT_ID=$(grep -oP 'client_id\s*=\s*"\K[^"]+' epac.tf)
          CLIENT_SECRET=$(grep -oP 'client_secret\s*=\s*"\K[^"]+' epac.tf)
          SUBSCRIPTION_ID=$(grep -oP 'subscription_id\s*=\s*"\K[^"]+' epac.tf)
          TENANT_ID=$(grep -oP 'tenant_id\s*=\s*"\K[^"]+' epac.tf)

          echo "CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
          echo "CLIENT_SECRET=$CLIENT_SECRET" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID=$SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "TENANT_ID=$TENANT_ID" >> $GITHUB_ENV

      - name: Debug Extracted Credentials
        run: |
          echo "CLIENT_ID: ${CLIENT_ID:0:5}**********"
          echo "SUBSCRIPTION_ID: ${SUBSCRIPTION_ID:0:5}**********"
          echo "TENANT_ID: ${TENANT_ID:0:5}**********"
          echo "CLIENT_SECRET: ********** (Hidden)"

      - name: Azure Login (Fix Special Characters Issue)
        run: |
          az login --service-principal --username "$CLIENT_ID" --password '${{ env.CLIENT_SECRET }}' --tenant "$TENANT_ID"

      - name: Set Azure Subscription
        run: |
          az account set --subscription "$SUBSCRIPTION_ID"

      - name: Verify Login
        run: az account show

      - name: Upload Terraform Files to Azure Storage
        run: |
          az storage blob upload-batch --account-name strepac --destination conepac --source . --pattern "*.tf" --overwrite --auth-mode login

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Set Azure Authentication Environment Variables
        run: |
          export ARM_CLIENT_ID=$CLIENT_ID
          export ARM_CLIENT_SECRET=$CLIENT_SECRET
          export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
          export ARM_TENANT_ID=$TENANT_ID

      - name: Initialize Terraform
        run: terraform init

      - name: Remove Local Terraform State File (if exists)
        run: rm -f terraform.tfstate

      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve
