name: Sync and Deploy Terraform Configuration

on:
  push:
    paths:
      - 'epac.tf'  # Trigger workflow when Terraform file changes

jobs:
  sync-upload-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Extract Azure Credentials
        id: extract-creds
        run: |
          CLIENT_ID=$(grep -oP 'client_id\s*=\s*"\K[^"]+' epac.tf)
          CLIENT_SECRET=$(grep -oP 'client_secret\s*=\s*"\K[^"]+' epac.tf)
          TENANT_ID=$(grep -oP 'tenant_id\s*=\s*"\K[^"]+' epac.tf)
          SUBSCRIPTION_ID=$(grep -oP 'subscription_id\s*=\s*"\K[^"]+' epac.tf)

          # Securely store them as environment variables
          echo "ARM_CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$CLIENT_SECRET" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$TENANT_ID" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID" >> $GITHUB_ENV

      - name: Log in to Azure CLI
        run: |
          az login --service-principal -u $CLIENT_ID -p="$CLIENT_SECRET" --tenant $TENANT_ID

      - name: Upload Terraform Files to Azure Storage
        run: |
          az storage blob upload-batch --account-name strepac --destination conepac --source . --pattern "*.tf" --overwrite --auth-mode login

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Set Azure Authentication Environment Variables
        run: |
          export ARM_CLIENT_ID=$CLIENT_ID
          export ARM_CLIENT_SECRET=$CLIENT_SECRET
          export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
          export ARM_TENANT_ID=$TENANT_ID

      - name: Initialize Terraform
        run: terraform init

      - name: Remove Local Terraform State File (if exists)
        run: rm -f terraform.tfstate

      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve
